#!/usr/bin/env zsh

num=`echo $DISPLAY | awk -F "" '{print $2}'`
screen=`echo $DISPLAY | awk -F "" '{print $4}'` 
new_num=`expr $num + 1`
test=`pidof Xephyr`
if [ $test ]
then
    echo "another instance of Xephyr exists (pid=$test)"
else
    {(Xephyr -ac ":$new_num" &> /dev/null) &;
      sleep 0.1s;
      export DISPLAY=":$new_num.$screen";
      (java $* &> /dev/null) &;
      export DISPLAY=":$num.$screen";
    }
fi
