#!/usr/bin/env zsh

# default option
SIZE=""
WM=""

# load configuration
if [ -e ~/.javawesomerc ]
then
  source ~/.javasomerc
fi

# setup configuration
if [ $SIZE ]
then
  screen_arg = "--screen $SCREEN_SIZE"
fi

num=`echo $DISPLAY | awk -F "" '{print $2}'`
screen=`echo $DISPLAY | awk -F "" '{print $4}'` 
new_num=`expr $num + 1`
test=`pidof Xephyr`
if [ $test ]
then
    echo "another instance of Xephyr exists (pid=$test)"
else
    {(Xephyr -ac ":$new_num" -reset -terminate &> /dev/null) &;
      xpid=$!
      sleep 0.1s;
      export DISPLAY=":$new_num.$screen";

      if [ $WM ]
      then
        $WM &
      fi

      java $*
      export DISPLAY=":$num.$screen";
      wait $xpid
    }
fi
