#!/usr/bin/env zsh

source ~/.javawesomerc

screen_arg="-screen"

num=`echo $DISPLAY | awk -F "" '{print $2}'`
screen=`echo $DISPLAY | awk -F "" '{print $4}'` 
new_num=`expr $num + 1`

pids=`pidof Xephyr`

if [ $pids ]
then
	{
	export DISPLAY=":$new_num.$screen";
  echo "$DISPLAY"
	$1;
	export DISPLAY=":$num.$screen";

	}
else
	echo "server not running";
fi
		
